- name: "1.7.6 Ensure permissions on /etc/issue.net are configured (Automated)"
  hosts: workstation
  become: true
  tasks:
    - name: Audit
      block:
      - name: Gather info on issue.net file
        stat:
          path: /etc/issue.net
        register: res

      - name: Fail if we do not find issue.net file
        fail: 
          msg: issue.net file not present!
        when: not res.stat.exists

      - name: Fail if permissions are incorrect
        fail:
          msg: "Permissions are not compliant, they are: mode={{res.stat['mode']}}, gid={{res.stat['gid']}}, uid={{res.stat['uid']}}"
        when: (res.stat['mode']!="0644") or (res.stat['gid']!=0) or (res.stat['uid']!=0) and (res.stat.exists)
      
      rescue:
        - debug:
            msg: |
              Audit found following:
              {% if res.stat.exists %}
                Your issue.net permissions are not compliant!
              {% else %}
                Your issue.net is not present!
              {% endif %}
      tags:
      - audit
    
    - name: Remediation
      block:
      - name: Warn if the file is not present
        debug:
          msg: Your issue.net is not present!
        when: not res.stat.exists
      - name: Set compliant permissions
        file:
          path: /etc/issue.net
          owner: root
          group: root
          mode: u=rw,g=r,o=r
        when: res.stat.exists   
      tags:
        - remediation  