- name: "1.7.1 Ensure message of the day is configured properly (Automated)"
  hosts: workstation
  become: true
  tasks:
    - name: Audit
      block:
      - name: Check MOTD file
        stat:
          path: /etc/motd
        register: res

      - name: Fail if we do not find MOTD
        fail: 
          msg: MOTD not present!
        when: not res.stat.exists

      - name: Fail if contents are invalid
        command: >
          grep -E -i "(\\\v|\\\r|\\\m|\\\s|$(grep '^ID=' /etc/os-release | cut -d= -f2 | sed -e 's/\"//g'))" /etc/motd
        register: motd_c
        failed_when: motd_c.stdout != ""
      
      rescue:
        - debug:
            msg: |
              Audit found following:
              {% if res.stat.exists %}
                Your motd contents are not compliant!
              {% else %}
                Your motd is not present!
              {% endif %}
      tags:
      - audit
    
    - name: Remediation
      block: 
      - name: Set copmpliant motd file
        template:
          src: motd.j2
          dest: /etc/motd
          owner: root
          group: root
          mode: u=rw,g=r,o=r
      tags:
        - remediation
     
    - name: Remediation_alt
      block: 
      - name: We do not need motd
        file:
          path: /etc/motd
          state: absent
      tags:
        - remediation_alt
        - never 