- name: "1.7.1 Ensure message of the day is configured properly (Automated)"
  hosts: workstation
  become: true
  tasks:
    - name: Audit
      block:
      - name: Check MOTD file
        stat:
          path: /etc/motd
        register: res
        tags: 
          - audit
          - permissions

      - name: Warn if we do not find MOTD
        debug: 
          msg: MOTD not present!
        when: not res.stat.exists

      - name: check for invalid contents
        command: >
          grep -E -i "(\\\v|\\\r|\\\m|\\\s|$(grep '^ID=' /etc/os-release | cut -d= -f2 | sed -e 's/\"//g'))" /etc/motd
        register: motd_c
        when: res.stat.exists
        failed_when: motd_c.stdout != ""
        tags:
          - audit

      - name: Warn if we find invalid contents
        debug:
          msg: "MOTD contains following illegal symbols {{motd_c.stdout}}"
        when: motd_c.stdout != ""
      
      rescue:
        - debug:
            msg: "Rescue triggered with {{res}}"
      tags:
      - audit
    
    - name: Remediation
      block: 
      - name: Set copmpliant motd file
        template:
          src: motd.j2
          dest: /etc/motd
          owner: root
          group: root
          mode: u=rw,g=r,o=r
          tags:
            - remediation
      tags:
        - remediation 